language: go

sudo: false

services:
  - docker

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - tip

before_install:
  - go get -t -v ./...

script:
  - ./.travis/tests.sh
  - docker build -t $TRAVIS_REPO_SLUG .

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    skip_cleanup: true
    script: bash .travis/docker_push
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash .travis/docker_push
    on:
      tags: true
